app:
  session:
    jwt:
      expiration-seconds: 900 # 15 minutes
      secret: secret123456789012345678901234567890
    refresh-token:
      length: 64
    expiration-seconds: 2592000 # 30 days

debug: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keepflower
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog-dev.yaml
  jpa:
    show-sql: true