app:
  session:
    jwt:
      expiration-seconds: ${JWT_EXPIRATION_SECONDS}
      secret: ${JWT_SECRET} # at least 32 chars
    refresh-token:
      length: ${REFRESH_TOKEN_LENGTH}
    expiration-seconds: ${SESSION_EXPIRATION_SECONDS}

spring:
  application:
    name: keepflower-api
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
