app:
  session:
    jwt:
      expirationSeconds: 900 # 15 minutes
      secret: ${JWT_SECRET:secret123456789012345678901234567890}
    expiration-seconds: 2592000 # 30 days

spring:
  application:
    name: keepflower-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/keepflower}
    username: ${DB_USERNAME:keepflower}
    password: ${DB_PASSWORD:keepflower}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false